# create docker-compose nginx for hosting hw.html

version: '3.8'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:9.6
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: "1"
    volumes:
      - telegram_bot_api_data:/var/lib/telegram-bot-api

  support-bot-py:
    image: ghcr.io/martins0n/homelab-services/support-bot-py:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8082:8000"
    env_file:
      - ../stack.env
    volumes:
      - telegram_bot_api_data:/var/lib/telegram-bot-api
    depends_on:
      - telegram-bot-api

volumes:
  telegram_bot_api_data:
