name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: support-bot-py
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi==0.114.0 openai httpx loguru pydantic-settings pytest pytest-asyncio
      - name: Run tests
        env:
          TELEGRAM_TOKEN: test
          DATABASE_URL: http://localhost
          DATABASE_KEY: key
          SUMMARY_QUEUE_URL: http://localhost
          YA_API: key
          X_TELEGRAM_BOT_HEADER: header
          OPENAI_API_KEY: dummy
        run: |
          PYTHONPATH=. pytest -q
